// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NameNodeRpcModel.proto

package com.hepo.dfs.namenode.rpc.model;

public interface AllocateDataNodesResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.hepo.dfs.namenode.rpc.AllocateDataNodesResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string datanodes = 1;</code>
   * @return The datanodes.
   */
  String getDatanodes();
  /**
   * <code>string datanodes = 1;</code>
   * @return The bytes for datanodes.
   */
  com.google.protobuf.ByteString
      getDatanodesBytes();
}
