// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NameNodeRpcModel.proto

package com.hepo.dfs.namenode.rpc.model;

public interface ChooseDataNodeFromReplicasResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.hepo.dfs.namenode.rpc.ChooseDataNodeFromReplicasResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string dataNodeInfo = 1;</code>
   * @return The dataNodeInfo.
   */
  String getDataNodeInfo();
  /**
   * <code>string dataNodeInfo = 1;</code>
   * @return The bytes for dataNodeInfo.
   */
  com.google.protobuf.ByteString
      getDataNodeInfoBytes();
}
