// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NameNodeRpcModel.proto

package com.hepo.dfs.namenode.rpc.model;

public interface HeartbeatResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.hepo.dfs.namenode.rpc.HeartbeatResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 status = 1;</code>
   * @return The status.
   */
  int getStatus();

  /**
   * <code>string commands = 2;</code>
   * @return The commands.
   */
  String getCommands();
  /**
   * <code>string commands = 2;</code>
   * @return The bytes for commands.
   */
  com.google.protobuf.ByteString
      getCommandsBytes();
}
