// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NameNodeRpcModel.proto

package com.hepo.dfs.namenode.rpc.model;

public interface HeartbeatRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.hepo.dfs.namenode.rpc.HeartbeatRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string ip = 1;</code>
   */
  String getIp();
  /**
   * <code>optional string ip = 1;</code>
   */
  com.google.protobuf.ByteString
      getIpBytes();

  /**
   * <code>optional string hostname = 2;</code>
   */
  String getHostname();
  /**
   * <code>optional string hostname = 2;</code>
   */
  com.google.protobuf.ByteString
      getHostnameBytes();
}
