// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NameNodeRpcModel.proto

package com.hepo.dfs.namenode.rpc.model;

public interface MkdirResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.hepo.dfs.namenode.rpc.MkdirResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 status = 1;</code>
   * @return The status.
   */
  int getStatus();
}
