// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NameNodeRpcModel.proto

package com.hepo.dfs.namenode.rpc.model;

public final class NameNodeRpcModel {
  private NameNodeRpcModel() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hepo_dfs_namenode_rpc_RegisterRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hepo_dfs_namenode_rpc_RegisterRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hepo_dfs_namenode_rpc_RegisterResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hepo_dfs_namenode_rpc_RegisterResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hepo_dfs_namenode_rpc_HeartbeatRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hepo_dfs_namenode_rpc_HeartbeatRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hepo_dfs_namenode_rpc_HeartbeatResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hepo_dfs_namenode_rpc_HeartbeatResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hepo_dfs_namenode_rpc_MkdirRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hepo_dfs_namenode_rpc_MkdirRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hepo_dfs_namenode_rpc_MkdirResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hepo_dfs_namenode_rpc_MkdirResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hepo_dfs_namenode_rpc_DeleteRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hepo_dfs_namenode_rpc_DeleteRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hepo_dfs_namenode_rpc_DeleteResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hepo_dfs_namenode_rpc_DeleteResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hepo_dfs_namenode_rpc_RenameRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hepo_dfs_namenode_rpc_RenameRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hepo_dfs_namenode_rpc_RenameResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hepo_dfs_namenode_rpc_RenameResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hepo_dfs_namenode_rpc_ShutdownRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hepo_dfs_namenode_rpc_ShutdownRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hepo_dfs_namenode_rpc_ShutdownResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hepo_dfs_namenode_rpc_ShutdownResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hepo_dfs_namenode_rpc_FetchEditsLogRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hepo_dfs_namenode_rpc_FetchEditsLogRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hepo_dfs_namenode_rpc_FetchEditsLogResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hepo_dfs_namenode_rpc_FetchEditsLogResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hepo_dfs_namenode_rpc_UpdateCheckpointTxidRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hepo_dfs_namenode_rpc_UpdateCheckpointTxidRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hepo_dfs_namenode_rpc_UpdateCheckpointTxidResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hepo_dfs_namenode_rpc_UpdateCheckpointTxidResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hepo_dfs_namenode_rpc_CreateFileRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hepo_dfs_namenode_rpc_CreateFileRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hepo_dfs_namenode_rpc_CreateFileResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hepo_dfs_namenode_rpc_CreateFileResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hepo_dfs_namenode_rpc_AllocateDataNodesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hepo_dfs_namenode_rpc_AllocateDataNodesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hepo_dfs_namenode_rpc_AllocateDataNodesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hepo_dfs_namenode_rpc_AllocateDataNodesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hepo_dfs_namenode_rpc_InformReplicaReceivedRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hepo_dfs_namenode_rpc_InformReplicaReceivedRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hepo_dfs_namenode_rpc_InformReplicaReceivedResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hepo_dfs_namenode_rpc_InformReplicaReceivedResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hepo_dfs_namenode_rpc_ReportCompleteStorageInfoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hepo_dfs_namenode_rpc_ReportCompleteStorageInfoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hepo_dfs_namenode_rpc_ReportCompleteStorageInfoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hepo_dfs_namenode_rpc_ReportCompleteStorageInfoResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hepo_dfs_namenode_rpc_ChooseDataNodeFromReplicasRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hepo_dfs_namenode_rpc_ChooseDataNodeFromReplicasRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hepo_dfs_namenode_rpc_ChooseDataNodeFromReplicasResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hepo_dfs_namenode_rpc_ChooseDataNodeFromReplicasResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hepo_dfs_namenode_rpc_ReallocateDataNodeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hepo_dfs_namenode_rpc_ReallocateDataNodeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hepo_dfs_namenode_rpc_ReallocateDataNodeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hepo_dfs_namenode_rpc_ReallocateDataNodeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hepo_dfs_namenode_rpc_RebalanceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hepo_dfs_namenode_rpc_RebalanceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hepo_dfs_namenode_rpc_RebalanceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hepo_dfs_namenode_rpc_RebalanceResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\026NameNodeRpcModel.proto\022\031com.hepo.dfs.n" +
      "amenode.rpc\"I\n\017RegisterRequest\022\n\n\002ip\030\001 \001" +
      "(\t\022\020\n\010hostname\030\002 \001(\t\022\030\n\020uploadServerPort" +
      "\030\003 \001(\005\"\"\n\020RegisterResponse\022\016\n\006status\030\001 \001" +
      "(\005\"0\n\020HeartbeatRequest\022\n\n\002ip\030\001 \001(\t\022\020\n\010ho" +
      "stname\030\002 \001(\t\"5\n\021HeartbeatResponse\022\016\n\006sta" +
      "tus\030\001 \001(\005\022\020\n\010commands\030\002 \001(\t\"\034\n\014MkdirRequ" +
      "est\022\014\n\004path\030\001 \001(\t\"\037\n\rMkdirResponse\022\016\n\006st" +
      "atus\030\001 \001(\005\"\035\n\rDeleteRequest\022\014\n\004path\030\001 \001(" +
      "\t\" \n\016DeleteResponse\022\016\n\006status\030\001 \001(\005\"\035\n\rR" +
      "enameRequest\022\014\n\004path\030\001 \001(\t\" \n\016RenameResp" +
      "onse\022\016\n\006status\030\001 \001(\005\"\037\n\017ShutdownRequest\022" +
      "\014\n\004code\030\001 \001(\005\"\"\n\020ShutdownResponse\022\016\n\006sta" +
      "tus\030\001 \001(\005\"8\n\024FetchEditsLogRequest\022\014\n\004cod" +
      "e\030\001 \001(\005\022\022\n\nsyncedTxid\030\002 \001(\003\")\n\025FetchEdit" +
      "sLogResponse\022\020\n\010editsLog\030\001 \001(\t\"+\n\033Update" +
      "CheckpointTxidRequest\022\014\n\004txid\030\001 \001(\003\".\n\034U" +
      "pdateCheckpointTxidResponse\022\016\n\006status\030\001 " +
      "\001(\005\"%\n\021CreateFileRequest\022\020\n\010filename\030\001 \001" +
      "(\t\"$\n\022CreateFileResponse\022\016\n\006status\030\001 \001(\005" +
      "\">\n\030AllocateDataNodesRequest\022\020\n\010filename" +
      "\030\001 \001(\t\022\020\n\010fileSize\030\002 \001(\003\".\n\031AllocateData" +
      "NodesResponse\022\021\n\tdatanodes\030\001 \001(\t\"N\n\034Info" +
      "rmReplicaReceivedRequest\022\n\n\002ip\030\001 \001(\t\022\020\n\010" +
      "hostname\030\002 \001(\t\022\020\n\010filename\030\003 \001(\t\"/\n\035Info" +
      "rmReplicaReceivedResponse\022\016\n\006status\030\001 \001(" +
      "\005\"l\n ReportCompleteStorageInfoRequest\022\n\n" +
      "\002ip\030\001 \001(\t\022\020\n\010hostname\030\002 \001(\t\022\021\n\tfilenames" +
      "\030\003 \001(\t\022\027\n\017storageDataSize\030\004 \001(\003\"3\n!Repor" +
      "tCompleteStorageInfoResponse\022\016\n\006status\030\001" +
      " \001(\005\"Q\n!ChooseDataNodeFromReplicasReques" +
      "t\022\020\n\010filename\030\001 \001(\t\022\032\n\022excludedDataNodeI" +
      "d\030\002 \001(\t\":\n\"ChooseDataNodeFromReplicasRes" +
      "ponse\022\024\n\014dataNodeInfo\030\001 \001(\t\"[\n\031Reallocat" +
      "eDataNodeRequest\022\020\n\010filename\030\001 \001(\t\022\020\n\010fi" +
      "leSize\030\002 \001(\003\022\032\n\022excludedDataNodeId\030\003 \001(\t" +
      "\".\n\032ReallocateDataNodeResponse\022\020\n\010datano" +
      "de\030\001 \001(\t\"\022\n\020RebalanceRequest\"#\n\021Rebalanc" +
      "eResponse\022\016\n\006status\030\001 \001(\005B5\n\037com.hepo.df" +
      "s.namenode.rpc.modelB\020NameNodeRpcModelP\001" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_hepo_dfs_namenode_rpc_RegisterRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_hepo_dfs_namenode_rpc_RegisterRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hepo_dfs_namenode_rpc_RegisterRequest_descriptor,
        new String[] { "Ip", "Hostname", "UploadServerPort", });
    internal_static_com_hepo_dfs_namenode_rpc_RegisterResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_hepo_dfs_namenode_rpc_RegisterResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hepo_dfs_namenode_rpc_RegisterResponse_descriptor,
        new String[] { "Status", });
    internal_static_com_hepo_dfs_namenode_rpc_HeartbeatRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_hepo_dfs_namenode_rpc_HeartbeatRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hepo_dfs_namenode_rpc_HeartbeatRequest_descriptor,
        new String[] { "Ip", "Hostname", });
    internal_static_com_hepo_dfs_namenode_rpc_HeartbeatResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_hepo_dfs_namenode_rpc_HeartbeatResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hepo_dfs_namenode_rpc_HeartbeatResponse_descriptor,
        new String[] { "Status", "Commands", });
    internal_static_com_hepo_dfs_namenode_rpc_MkdirRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_hepo_dfs_namenode_rpc_MkdirRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hepo_dfs_namenode_rpc_MkdirRequest_descriptor,
        new String[] { "Path", });
    internal_static_com_hepo_dfs_namenode_rpc_MkdirResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_hepo_dfs_namenode_rpc_MkdirResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hepo_dfs_namenode_rpc_MkdirResponse_descriptor,
        new String[] { "Status", });
    internal_static_com_hepo_dfs_namenode_rpc_DeleteRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_hepo_dfs_namenode_rpc_DeleteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hepo_dfs_namenode_rpc_DeleteRequest_descriptor,
        new String[] { "Path", });
    internal_static_com_hepo_dfs_namenode_rpc_DeleteResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_com_hepo_dfs_namenode_rpc_DeleteResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hepo_dfs_namenode_rpc_DeleteResponse_descriptor,
        new String[] { "Status", });
    internal_static_com_hepo_dfs_namenode_rpc_RenameRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_com_hepo_dfs_namenode_rpc_RenameRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hepo_dfs_namenode_rpc_RenameRequest_descriptor,
        new String[] { "Path", });
    internal_static_com_hepo_dfs_namenode_rpc_RenameResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_com_hepo_dfs_namenode_rpc_RenameResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hepo_dfs_namenode_rpc_RenameResponse_descriptor,
        new String[] { "Status", });
    internal_static_com_hepo_dfs_namenode_rpc_ShutdownRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_com_hepo_dfs_namenode_rpc_ShutdownRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hepo_dfs_namenode_rpc_ShutdownRequest_descriptor,
        new String[] { "Code", });
    internal_static_com_hepo_dfs_namenode_rpc_ShutdownResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_com_hepo_dfs_namenode_rpc_ShutdownResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hepo_dfs_namenode_rpc_ShutdownResponse_descriptor,
        new String[] { "Status", });
    internal_static_com_hepo_dfs_namenode_rpc_FetchEditsLogRequest_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_com_hepo_dfs_namenode_rpc_FetchEditsLogRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hepo_dfs_namenode_rpc_FetchEditsLogRequest_descriptor,
        new String[] { "Code", "SyncedTxid", });
    internal_static_com_hepo_dfs_namenode_rpc_FetchEditsLogResponse_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_com_hepo_dfs_namenode_rpc_FetchEditsLogResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hepo_dfs_namenode_rpc_FetchEditsLogResponse_descriptor,
        new String[] { "EditsLog", });
    internal_static_com_hepo_dfs_namenode_rpc_UpdateCheckpointTxidRequest_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_com_hepo_dfs_namenode_rpc_UpdateCheckpointTxidRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hepo_dfs_namenode_rpc_UpdateCheckpointTxidRequest_descriptor,
        new String[] { "Txid", });
    internal_static_com_hepo_dfs_namenode_rpc_UpdateCheckpointTxidResponse_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_com_hepo_dfs_namenode_rpc_UpdateCheckpointTxidResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hepo_dfs_namenode_rpc_UpdateCheckpointTxidResponse_descriptor,
        new String[] { "Status", });
    internal_static_com_hepo_dfs_namenode_rpc_CreateFileRequest_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_com_hepo_dfs_namenode_rpc_CreateFileRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hepo_dfs_namenode_rpc_CreateFileRequest_descriptor,
        new String[] { "Filename", });
    internal_static_com_hepo_dfs_namenode_rpc_CreateFileResponse_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_com_hepo_dfs_namenode_rpc_CreateFileResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hepo_dfs_namenode_rpc_CreateFileResponse_descriptor,
        new String[] { "Status", });
    internal_static_com_hepo_dfs_namenode_rpc_AllocateDataNodesRequest_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_com_hepo_dfs_namenode_rpc_AllocateDataNodesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hepo_dfs_namenode_rpc_AllocateDataNodesRequest_descriptor,
        new String[] { "Filename", "FileSize", });
    internal_static_com_hepo_dfs_namenode_rpc_AllocateDataNodesResponse_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_com_hepo_dfs_namenode_rpc_AllocateDataNodesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hepo_dfs_namenode_rpc_AllocateDataNodesResponse_descriptor,
        new String[] { "Datanodes", });
    internal_static_com_hepo_dfs_namenode_rpc_InformReplicaReceivedRequest_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_com_hepo_dfs_namenode_rpc_InformReplicaReceivedRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hepo_dfs_namenode_rpc_InformReplicaReceivedRequest_descriptor,
        new String[] { "Ip", "Hostname", "Filename", });
    internal_static_com_hepo_dfs_namenode_rpc_InformReplicaReceivedResponse_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_com_hepo_dfs_namenode_rpc_InformReplicaReceivedResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hepo_dfs_namenode_rpc_InformReplicaReceivedResponse_descriptor,
        new String[] { "Status", });
    internal_static_com_hepo_dfs_namenode_rpc_ReportCompleteStorageInfoRequest_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_com_hepo_dfs_namenode_rpc_ReportCompleteStorageInfoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hepo_dfs_namenode_rpc_ReportCompleteStorageInfoRequest_descriptor,
        new String[] { "Ip", "Hostname", "Filenames", "StorageDataSize", });
    internal_static_com_hepo_dfs_namenode_rpc_ReportCompleteStorageInfoResponse_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_com_hepo_dfs_namenode_rpc_ReportCompleteStorageInfoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hepo_dfs_namenode_rpc_ReportCompleteStorageInfoResponse_descriptor,
        new String[] { "Status", });
    internal_static_com_hepo_dfs_namenode_rpc_ChooseDataNodeFromReplicasRequest_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_com_hepo_dfs_namenode_rpc_ChooseDataNodeFromReplicasRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hepo_dfs_namenode_rpc_ChooseDataNodeFromReplicasRequest_descriptor,
        new String[] { "Filename", "ExcludedDataNodeId", });
    internal_static_com_hepo_dfs_namenode_rpc_ChooseDataNodeFromReplicasResponse_descriptor =
      getDescriptor().getMessageTypes().get(25);
    internal_static_com_hepo_dfs_namenode_rpc_ChooseDataNodeFromReplicasResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hepo_dfs_namenode_rpc_ChooseDataNodeFromReplicasResponse_descriptor,
        new String[] { "DataNodeInfo", });
    internal_static_com_hepo_dfs_namenode_rpc_ReallocateDataNodeRequest_descriptor =
      getDescriptor().getMessageTypes().get(26);
    internal_static_com_hepo_dfs_namenode_rpc_ReallocateDataNodeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hepo_dfs_namenode_rpc_ReallocateDataNodeRequest_descriptor,
        new String[] { "Filename", "FileSize", "ExcludedDataNodeId", });
    internal_static_com_hepo_dfs_namenode_rpc_ReallocateDataNodeResponse_descriptor =
      getDescriptor().getMessageTypes().get(27);
    internal_static_com_hepo_dfs_namenode_rpc_ReallocateDataNodeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hepo_dfs_namenode_rpc_ReallocateDataNodeResponse_descriptor,
        new String[] { "Datanode", });
    internal_static_com_hepo_dfs_namenode_rpc_RebalanceRequest_descriptor =
      getDescriptor().getMessageTypes().get(28);
    internal_static_com_hepo_dfs_namenode_rpc_RebalanceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hepo_dfs_namenode_rpc_RebalanceRequest_descriptor,
        new String[] { });
    internal_static_com_hepo_dfs_namenode_rpc_RebalanceResponse_descriptor =
      getDescriptor().getMessageTypes().get(29);
    internal_static_com_hepo_dfs_namenode_rpc_RebalanceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hepo_dfs_namenode_rpc_RebalanceResponse_descriptor,
        new String[] { "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
