// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NameNodeRpcModel.proto

package com.hepo.dfs.namenode.rpc.model;

public interface ReallocateDataNodeResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.hepo.dfs.namenode.rpc.ReallocateDataNodeResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string datanode = 1;</code>
   * @return The datanode.
   */
  String getDatanode();
  /**
   * <code>string datanode = 1;</code>
   * @return The bytes for datanode.
   */
  com.google.protobuf.ByteString
      getDatanodeBytes();
}
