// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NameNodeRpcModel.proto

package com.hepo.dfs.namenode.rpc.model;

public interface ReportCompleteStorageInfoRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.hepo.dfs.namenode.rpc.ReportCompleteStorageInfoRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string ip = 1;</code>
   * @return The ip.
   */
  String getIp();
  /**
   * <code>string ip = 1;</code>
   * @return The bytes for ip.
   */
  com.google.protobuf.ByteString
      getIpBytes();

  /**
   * <code>string hostname = 2;</code>
   * @return The hostname.
   */
  String getHostname();
  /**
   * <code>string hostname = 2;</code>
   * @return The bytes for hostname.
   */
  com.google.protobuf.ByteString
      getHostnameBytes();

  /**
   * <code>string filenames = 3;</code>
   * @return The filenames.
   */
  String getFilenames();
  /**
   * <code>string filenames = 3;</code>
   * @return The bytes for filenames.
   */
  com.google.protobuf.ByteString
      getFilenamesBytes();

  /**
   * <code>int64 storageDataSize = 4;</code>
   * @return The storageDataSize.
   */
  long getStorageDataSize();
}
