// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NameNodeRpcModel.proto

package com.hepo.dfs.namenode.rpc.model;

public interface UpdateCheckpointTxidRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.hepo.dfs.namenode.rpc.UpdateCheckpointTxidRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 txid = 1;</code>
   * @return The txid.
   */
  long getTxid();
}
