// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NameNodeRpcServer.proto

package com.hepo.dfs.namenode.rpc.service;

public final class NameNodeServer {
  private NameNodeServer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\027NameNodeRpcServer.proto\022\031com.hepo.dfs." +
      "namenode.rpc\032\026NameNodeRpcModel.proto2\272\002\n" +
      "\017NameNodeService\022c\n\010register\022*.com.hepo." +
      "dfs.namenode.rpc.RegisterRequest\032+.com.z" +
      "hss.dfs.namenode.rpc.RegisterResponse\022f\n" +
      "\theartbeat\022+.com.hepo.dfs.namenode.rpc.H" +
      "eartbeatRequest\032,.com.hepo.dfs.namenode." +
      "rpc.HeartbeatResponse\022Z\n\005mkdir\022\'.com.zhs" +
      "s.dfs.namenode.rpc.MkdirRequest\032(.com.zh" +
      "ss.dfs.namenode.rpc.MkdirResponseB5\n!com",
      ".hepo.dfs.namenode.rpc.serviceB\016NameNode" +
      "ServerP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.hepo.dfs.namenode.rpc.model.NameNodeRpcModel.getDescriptor(),
        }, assigner);
    com.hepo.dfs.namenode.rpc.model.NameNodeRpcModel.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
